language: generic
sudo: required
dist: trusty

#slack integration
notifications:
  email: false
  slack:
    rooms:
      - secure: "1X6t6P/RL97qAXY+nx9JHovMOcgTmvIwRRWOAJqL44Z4ypWtp8XJnU/pHjFYCW7JYe5TFpobEWrrnjORasrVH8rGU/n1pqHxFwJiAsmlDej1fqWcC0A8P1cj6OtbfEWw/az2FaFoP3G7+DejeFWVWWjgpUCpeFfw06fzSHAv6wdoISSSaFmWhgNHctaZuZJsTRrn1B9CMSEGGTV0RTnKSCo76cDd8XgG5bGBqbzOg8rK4jFtnb9VEObxHCK6zdx92vflZB25OC3QkJOE/86xhEQhmuyI3g7vUGd20Ioln93haeG2742/akhyfMXY0n8VPPTJwOeHUAzSKvHw0InTro0mtFP6I+YylgF/F58H3KD1j4G7/Sbe4WRA4tWUSv2FKVxhnHn5fp3DUKnBxiZ3pSGC5tW3cYduo+OVxcPO+Bxqx1CcnWEYTHsSU+5SoqPqyPAEf7w9QufBOPwXAlZ3if94eUBfpP17yaohlLpyPfLuKjSOkwbG3Gq0NRs2EYHSFB2qnPJap5ekATVRbtJnkFoI3dtvRIo5HuL670Y8pYUwAjADXpPmuWM0nxUh3arIOgr7o1dhQfkD5GJR48Ai27+Q6FuFto3+zqeIByWXeuUHbzXrAC++8whqLATTXIk3ONgfDrmo+M6jsihGb0E/NjjRnT3Az4w0nSGx3xPPHuw="
    on_success: always
    on_failure: always

#whitelist for branches to build
branches:
  only:
    - master
    - dev
    - travisci

#install dependencies
addons:
  apt:
    sources:
    - sourceline: 'deb http://packages.ros.org/ros/ubuntu trusty main'
      key_url: 'https://raw.githubusercontent.com/ros/rosdistro/master/ros.key '
    - sourceline: 'deb http://robosub.eecs.wsu.edu/repo/ /'
      key_url: 'http://robosub.eecs.wsu.edu/repo/repository_key'
    - sourceline: 'deb http://packages.osrfoundation.org/gazebo/ubuntu trusty main'
      key_url: 'http://packages.osrfoundation.org/gazebo.key'
    packages:
    - robosub
    - robosub-simulator

#build the project
before_script:
  - source /opt/ros/indigo/setup.bash
  - cd ../ && mkdir src && mv robosub_simulator src/ && cd src
  - catkin_init_workspace
  - cd ..
  - cd src/; git clone https://github.com/PalouseRobosub/robosub.git; git clone https://github.com/PalouseRobosub/robosub_msgs.git; cd ../

script:
  - if [ "$TEST" == "true" ] ; then catkin_make; source devel/setup.bash; catkin_make run_tests; catkin_test_results; fi
  - if [ "$LINT" == "true" ] ; then catkin_make roslint_robosub_simulator; fi

matrix:
    include:
        - env:
          - TEST=true
        - env:
          - LINT=true
