language: generic
sudo: required
dist: trusty

#slack integration
notifications:
  email: false
  slack:
    rooms:
      - palouserobosub:C883XOLXAI646jXLW8zENsVE#software
    on_success: never
    on_failure: never

#whitelist for branches to build
branches:
  only:
    - master
    - dev
    - travisci

#install dependencies
addons:
  apt:
    sources:
    - sourceline: 'deb http://mirror.umd.edu/packages.ros.org/ros/ubuntu trusty main'
      key_url: 'https://raw.githubusercontent.com/ros/rosdistro/master/ros.key '
    - sourceline: 'deb http://robosub.eecs.wsu.edu/repo/ /'
      key_url: 'http://robosub.eecs.wsu.edu/repo/repository_key'
    - sourceline: 'deb http://packages.osrfoundation.org/gazebo/ubuntu trusty main'
      key_url: 'http://packages.osrfoundation.org/gazebo.key'
    packages:
    - robosub
    - robosub-simulator

#build the project
before_script:
  - source /opt/ros/indigo/setup.bash
  - cd ../ && mkdir src && mv robosub_simulator src/ && cd src
  - catkin_init_workspace
  - cd ..
  - cd src/; git clone https://github.com/PalouseRobosub/robosub.git; cd ../

script:
  - catkin_make
  - source devel/setup.bash
  - catkin_make run_tests
  - catkin_test_results
